ABP.Strings={
	statsPlayer:'播放器尺寸：',
	statsVideo:'视频分辨率：',
	statsBuffer:'可用缓冲：',
	statsBufferClip:'缓冲片段：',
	statsPresent:'期望帧率：',
	statsDrop:'丢弃帧率：',
	statsMimetype:'文件格式：',
	statsVideoBitrate:'本段视频码率：',
	statsAudioBitrate:'本段音频码率：',
	statsCurrentBitrate:'本段码率：',
	statsRealtimeBitrate:'实时码率：',
	overallBitrate:'总体码率：',
	reload:'重新载入',
	statsDownloadSpeed:'下载速度：',
	statsSourceHost:'视频源域名：',
	statsRedirection:'重定向：',
	statsRedirectionNone:'否',
	copySegUrl:'复制地址',
	
	sendSmall:"小字号",
	sendMid:"中字号",
	sendSize:'弹幕字号',
	sendMode:"弹幕模式",
	sendTop:"顶端渐隐",
	sendScroll:"滚动字幕",
	sendBottom:"底端渐隐",
	send:"发送",
	sendStyle:"弹幕样式",
	sendColor:"弹幕颜色",
	
	commentSpeed:"弹幕速度",
	commentScale:"弹幕比例",
	commentDensity:'弹幕密度',
	commentOpacity:"弹幕不透明度",
	commentBlock:"弹幕屏蔽设定",
	
	playSpeed:"播放速度",
	playSpeedReset:"还原正常速度",
	
	displayScaleD:"默认",
	displayScaleF:"全屏",
	
	shieldTypeText:'文字',
	shieldTypeUser:'用户',
	shieldTypeColor:'颜色',
	shieldTypeSetting:'设置',
	shieldAdd:'添加屏蔽……',
	shieldUseRegex:'启用正则',
	shieldBlockTop:'屏蔽顶端弹幕',
	shieldBlockBottom:'屏蔽底端弹幕',
	shieldBlockVisitor:'屏蔽游客弹幕',
	shieldRepeat:'去除刷屏弹幕',
	
	viewers:' 观众',
	comments:' 弹幕',
	reconnectSocket:'重连弹幕服务器',
	commentTime:"时间",
	commentContent:"评论",
	commentDate:"发送日期",
	blockMatch:'命中规则：',
	
	showStats:'显示统计信息',
	
	loadingMeta:'正在加载视频信息',
	switching:'正在切换',
	fetchURL:'正在获取视频地址',
	buffering:'正在缓冲',
	play:'播放',
	next:'下一个: ',
	pause:'暂停',
	mute:'静音',
	unmute:'取消静音',
	muteNotSupported:'不支持静音',
	fullScreen:"浏览器全屏",
	exitFullScreen:"退出全屏",
	webFull:"网页全屏",
	exitWebFull:"退出网页全屏",
	cmtListShow:"显示弹幕列表",
	cmtListHide:"隐藏弹幕列表",
	sendTooltip:"毁灭地喷射白光!da!",
	showComment:"显示弹幕",
	hideComment:"隐藏弹幕",
	loopOn:"洗脑循环 on",
	loopOff:"洗脑循环 off",
	usingCanvas:'正在使用Canvas',
	usingCSS:'正在使用CSS',
	useCSS:'使用CSS绘制弹幕',
	autoOpacityOn:'关闭自动不透明度',
	autoOpacityOff:'开启自动不透明度',
	settings:'设置',
	
	copyComment:'复制弹幕',
	findComment:'定位弹幕',
	blockContent:'屏蔽内容“',
	blockUser:'屏蔽发送者',
	blockColor:'屏蔽颜色',
	blockColorWhite:'不能屏蔽白色',
	copied:'已复制',
	copyFail:'复制失败，浏览器不支持',
	
	blockUserEmpty:'没有屏蔽用户',
	blockColorEmpty:'没有屏蔽颜色',
	repeatPcs:'条',
	repeatUnlimited:'不限制',
	
	dragControlLowInc:'低速快进',
	dragControlLowDec:'低速快退',
	dragControlMedInc:'中速快进',
	dragControlMedDec:'中速快退',
	dragControlHighInc:'高速快进',
	dragControlHighDec:'高速快退',
	dragControlCancel:'取消跳转',
	
	settComment:'弹幕偏好设置',
	recordPlaySpeed:'将当前速度设为默认',
	settPlayer:'播放器偏好设置',
	autoPlay:'自动开始播放',
	defaultFull:'自动进入全屏模式',
	playerTheme:'播放器主题：',
	cmStyle: '弹幕样式：',
	cmStyle_st: '描边',
	cmStyle_sh: '阴影',
	cmStyle_stsh: '描边 + 阴影',

	volumeChange: '音量改变至 ',
	rateChange: '速度改变至 ',

	hasSubtitles: '视频包含字幕，可在设置中选择开启',
	mainSubtitle: '主要字幕：',
	secondarySubtitle: '次级字幕：',
	subtitleClosed: '关闭',

	screenshot: '视频截屏',
	screenshotWithoutComment: '不含弹幕',
	screenshotWithComment: '含弹幕',
	screenshotCSSNoSupport: 'css弹幕不支持截图',
	screenshotError: '视频源限制，无法生成截图'
}